<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="testinglaptop" ignored="0" name="Test" tests="13" failures="3" timestamp="2023-03-07T15:43:49 IST" time="0.011" errors="0">
  <testcase name="test1" time="0.0" classname="crm.vtiger.practice.TestNGPracticeClass2"/>
  <testcase name="test1" time="0.0" classname="crm.vtiger.practice.TestNGPracticeClass2"/>
  <testcase name="test1" time="0.0" classname="crm.vtiger.practice.TestNGPracticeClass2"/>
  <testcase name="test1" time="0.0" classname="crm.vtiger.practice.TestNGPracticeClass2"/>
  <testcase name="test1" time="0.0" classname="crm.vtiger.practice.TestNGPracticeClass2"/>
  <testcase name="test1" time="0.002" classname="crm.vtiger.practice.TestNGPracticeClass2"/>
  <testcase name="test1" time="0.0" classname="crm.vtiger.practice.TestNGPracticeClass2"/>
  <testcase name="test1" time="0.0" classname="crm.vtiger.practice.TestNGPracticeClass2"/>
  <testcase name="test1" time="0.0" classname="crm.vtiger.practice.TestNGPracticeClass2"/>
  <testcase name="test1" time="0.0" classname="crm.vtiger.practice.TestNGPracticeClass2"/>
  <testcase name="test1" time="0.0" classname="crm.vtiger.practice.TestNGPracticeClass3">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1] but found [2]
at crm.vtiger.practice.TestNGPracticeClass3.test1(TestNGPracticeClass3.java:24)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.001" classname="crm.vtiger.practice.TestNGPracticeClass3">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [b] but found [a]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [b] but found [a]
at crm.vtiger.practice.TestNGPracticeClass3.test2(TestNGPracticeClass3.java:32)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.0" classname="crm.vtiger.practice.TestNGPracticeClass3">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [2] but found [22]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [2] but found [22]
at crm.vtiger.practice.TestNGPracticeClass3.test3(TestNGPracticeClass3.java:40)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- Test -->
